### ISSUE TITLE
I'm unable to replicate your master image, or make yours work.

### ISSUE THREAD

**Issue by hartzell** [foxylion/docker-jenkins#1]
Thanks for putting this together, it's an incredible resource!   But...

I started off trying to set up my own images riff'ing off your your example, but could not get it to work.  So I cloned your repository, cd'ed into docker-images/master and ran `docker build .`

Then I ran:

```
docker run --name jenkins -p 8080:8080 -p 50000:50000 -v ~/tmp/blah:/var/jenkins_home e2a95803c8ab
```

where `e2a95803c8ab` is the id of the image I just built.

I am unable to log in as the user *admin* with the password *admin*, I get the error message:

```
Invalid login information. Please try again. 
Try again
```

I also just tried to run `foxylion/jenkins` like so:

```
docker run --name jenkins -p 8080:8080 -p 50000:50000 -v ~/tmp/blah:/var/jenkins_home foxylion/jenkins
```

and have the same problem.

After running the container there there is a file in `~/tmp/blah` called `users/admin/config.xml` that contains this (amongst more):

```xml
    <hudson.security.HudsonPrivateSecurityRealm_-Details>
      <passwordHash>#jbcrypt:$2a$10$NcvhiPxOKBd4SuwRxTXVnufLhrMhV6YTLQzZCn88iKy9vmVm3VYju</passwordHash>
    </hudson.security.HudsonPrivateSecurityRealm_-Details>
```

so it seems as if something is nearly there.

I suspect (Murphy requires!) that I'm doing something silly, but I can find it.

I don't see any logging info in the console or anywhere in `jenkins_home`.  Is there somewhere I can start digging?

**Comment by hartzell** [comment]
Thinking that this might have something to do with running docker and docker-machine on my mac, I started up one of the Digital Ocean docker images and tried running this:

```
docker run --name jenkins -p 80:8080 -p 50000:50000 -v /tmp/foo:/var/jenkins_home foxylion/jenkins
```

with the same result.  It pulls down the image, starts (and writes a bunch of stuff in /tmp/foo) but I can not log in as _admin_ using password _admin_.

**Comment by foxylion** [comment]
I'm sorry you ran into this issue, it is caused by not setting the default password properly.
You can change the password of the administrative user using the `JENKINS_PASS` environment variable.
I also fixed the issue in the docker image, so as soon as it's built the new Docker image should set the correct default password. But feel free to use it now with the `JENKINS_PASS` variable.

Commit fixing the issue: 74cbd03e0fdfba881a2d110131eabb4b74d4bb64

**Comment by hartzell** [comment]
"WORD"! I should have seen that it wasn't lining up with the way it was used in the default-user.groovy script.

Thank you for digging into it so quickly. This is a great resource, I wish it were mentioned in the JenkinsSci Jenkins Dockerfile repository.
