### ISSUE TITLE
default-user.groovy Jenkins.ADMINISTER username

### ISSUE THREAD

**Issue by mpettigr** [foxylion/docker-jenkins#2]
In docker-jenkins/docker-images/master/default-user.groovy,

the line

jenkins.getAuthorizationStrategy().add(Jenkins.ADMINISTER, 'admin')

uses the literal value 'admin' to set the user account to ADMINISTER privilege.  It seems like this should instead be

jenkins.getAuthorizationStrategy().add(Jenkins.ADMINISTER, env.JENKINS_USER)

so the newly created account has admin privileges.  As is, if the env variable JENKINS_USER isn't 'admin' ( say 'jenkins' instead ) the code doesn't work.

**Comment by foxylion** [comment]
Thanks for your report, I've fixed the issue and the docker images are being updated.
