### ISSUE TITLE
Should this read make build instead of make vagrant?

### ISSUE THREAD

**Issue by sirkkalap** [foxylion/docker-jenkins#4]
Sorry, but for me the build fails with error: "make: *** No rule to make target `vagrant'.  Stop." 

https://github.com/foxylion/docker-jenkins/blob/1d26e062a309bb3d7394517834403f78c35183a1/Vagrantfile#L13

**Comment by foxylion** [comment]
I'm sorry, the Vagrantfile is no longer usable. I just deleted it.
If you want to try it out start a linux virtual machine or install Docker for Windows/MacOS.
