### ISSUE TITLE
Add support for JNLP encryption

### ISSUE THREAD

**Issue by ipeacocks** [foxylion/docker-jenkins#6]
In Readme you have said:

"Note: Using a JNLP slave does not provide any encryption when communicating with the master. In an untrusted network this is not recommended. Use instead the ssh slave image."

But seems it's not true for now https://i.imgur.com/yHWlLn3.png. Am I correct?

**Comment by foxylion** [comment]
@ipeacocks I think the current JNLP slave uses the old, unencrypted, variant. But you can just try it out and report back which version the image uses. If you manage to get it working with encryption I'm happy to merge a pull request.

**Comment by ipeacocks** [comment]
As I can see from code:

```python
def slave_download(target):
    if os.path.isfile(slave_jar):
        os.remove(slave_jar)

    loader = urllib.URLopener()
    loader.retrieve(os.environ['JENKINS_URL'] + '/jnlpJars/slave.jar', '/var/lib/jenkins/slave.jar')

def slave_run(slave_jar, jnlp_url):
    params = [ 'java', '-jar', slave_jar, '-jnlpUrl', jnlp_url ]
    if os.environ['JENKINS_SLAVE_ADDRESS'] != '':
        params.extend([ '-connectTo', os.environ['JENKINS_SLAVE_ADDRESS' ] ])
```
Python launches code via JNLP protocol from Jenkins server (master) and it provides latest version of slave.

**Comment by foxylion** [comment]
@ipeacocks Does look good, had you a chance to try it out a test if it really works?
If yes, feel free to create a pull request that updates the documentation. :)
