### ISSUE TITLE
SSH agent docker could not expose its host "resource" to the Jenkins master

### ISSUE THREAD

**Issue by cw1427** [foxylion/docker-jenkins#8]
I bring up a slave via ssh-agent docker and setup some jobs running on it.  But the problem is the job running on this docker slave is isolated within the docker container, is there a good approach to expose the host resouce(the libs commands fs) to this jenkins slave running by ssh docker agent?

BTW, I source your example that running docker to mount the docker socket file into agent container, what is the reason you did this?

**Comment by foxylion** [comment]
Hi @cw1427,
we used an approach to always rely on containers when needing specific binaries/libraries/...

Therefore we exposed the docker socket of our host into the jenkins slave container. This allows the container to access the docker daemon to start other containers. By mounting the home directory of the jenkins slave from the outside filesystem this also allows to access a shared file system.

We made heavily use of the following pattern:

```
docker.image('node:14').inside {
  sh 'npm install'
  sh 'npm run build'
}
````
See https://www.jenkins.io/doc/book/pipeline/docker/ for more details
